name: pyladies-berlin-dask
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nodejs
  - dask>=2.30.0
  - distributed>=2.30.0
  - jupyterlab>=3
  - pandas>=1.0.1
  - bokeh>=2.2.0
  - ipywidgets
  - pip>=20.3.0
  - pip:
    - dask-labextension>=3.0.0
  - python-graphviz
  - coiled
