name: scale-with-dask
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - dask
  - distributed
  - jupyterlab
  - pandas
  - pip
  - dask-labextension
  - python-graphviz
  - coiled
  - boto3
  - s3fs>=2021.08.0
  - nodejs
